# fly.toml app configuration file generated for ataichi on 2025-04-27T22:24:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ataichi'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8334
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "ataichi"
  destination = "/app/data/state"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
